spring:
  application:
    name: journal-service
  profiles:
    active: local

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0